language: node_js
node_js:
  - 6
cache:
  directories:
  - node_modules
before_script:
  - npm prune
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: build
